#!/usr/bin/env python3
"""assemble.py — build the submission MP4 from existing assets.

Reuses build/audio/s*.mp3 (edge-tts, generated by narrate.py) and
build/frames/*.png (chromium screenshots). No network, no TTS re-run.

Scene -> visual map (matches narrate.py header):
  s0 23.6s  slide_01  cold open
  s1 27.5s  slide_05  what it trades + engine
  s2 37.6s  demo.png  terminal refusal cycle (real gate output)
  s3 35.0s  slide_06 + slide_07  gate stack, then portfolio shape (split ~55%)
  s4 32.0s  slide_10  10x account trap
  s5 32.4s  slide_12  close (+2s hold)
Canvas 1280x720, bg #05070b, h264 yuv420p + AAC. Narration total 3:08.
"""
import os, subprocess, sys

os.chdir(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
F = "build/frames"
A = "build/audio"
TMP = "build/segs"
os.makedirs(TMP, exist_ok=True)

def dur(p):
    return float(subprocess.check_output(
        ["ffprobe", "-v", "error", "-show_entries", "format=duration",
         "-of", "csv=p=0", p]).decode().strip())

PAD = "color=0x05070B"
VF = (f"scale=-2:720:force_original_aspect_ratio=decrease,"
      f"pad=1280:720:(ow-iw)/2:(oh-ih)/2:color=0x05070B,"
      f"format=yuv420p")

def segment(img, audio, out, tail=0.6):
    subprocess.run(["ffmpeg", "-y", "-v", "error",
        "-loop", "1", "-framerate", "30", "-i", img,
        "-i", audio,
        "-vf", VF,
        "-af", f"apad=pad_dur={tail}",
        "-c:v", "libx264", "-preset", "medium", "-crf", "18",
        "-c:a", "aac", "-b:a", "128k", "-ar", "44100",
        "-t", f"{dur(audio) + tail:.3f}",
        "-shortest", out], check=True)

# split s3 audio into two halves (gates slide, then portfolio slide)
s3 = f"{A}/s3.mp3"
half = dur(s3) * 0.55
for name, ss, to in [("s3a", "0", f"{half:.3f}"), ("s3b", f"{half:.3f}", None)]:
    cmd = ["ffmpeg", "-y", "-v", "error", "-i", s3, "-ss", ss]
    if to: cmd += ["-to", to]
    cmd += ["-c", "copy", f"{TMP}/{name}.mp3"]
    subprocess.run(cmd, check=True)

PLAN = [
    ("s0", f"{F}/slide_01.png", f"{A}/s0.mp3", 0.6),
    ("s1", f"{F}/slide_05.png", f"{A}/s1.mp3", 0.6),
    ("s2", f"{F}/demo.png",     f"{A}/s2.mp3", 0.8),
    ("s3a", f"{F}/slide_06.png", f"{TMP}/s3a.mp3", 0.15),
    ("s3b", f"{F}/slide_07.png", f"{TMP}/s3b.mp3", 0.6),
    ("s4", f"{F}/slide_10.png", f"{A}/s4.mp3", 0.6),
    ("s5", f"{F}/slide_11.png", f"{A}/s5.mp3", 0.6),
    ("s5b", f"{F}/slide_12.png", f"{A}/s5b.mp3", 2.0),
]
for tag, img, aud, tail in PLAN:
    segment(img, aud, f"{TMP}/{tag}.mp4", tail)
    print(tag, "ok", f"{dur(f'{TMP}/{tag}.mp4'):.1f}s")

with open(f"{TMP}/list.txt", "w") as fh:
    for tag, *_ in PLAN:
        fh.write(f"file '{tag}.mp4'\n")

subprocess.run(["ffmpeg", "-y", "-v", "error", "-f", "concat", "-safe", "0",
                "-i", f"{TMP}/list.txt", "-c", "copy",
                "-movflags", "+faststart", "build/slides-final.mp4"], check=True)
print("TOTAL", f"{dur('build/slides-final.mp4'):.1f}s")
